spring:
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST:mongodb.railway.internal}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
      database: ${SPRING_DATA_MONGODB_DATABASE:gallery}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  webmvc:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE
      allowed-headers: "*"

server:
  port: 8080
  address: 0.0.0.0

logging:
  level:
    org.springframework.web: INFO
    personal.gallery: DEBUG
